### PR TITLE
fix: validate authorization schema

### LINKED ISSUE #164: Authorization scheme not validated
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

9.1.0

### Node.js version

18.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.6.1

### Description

The plugin does not verify that the authentication scheme passed in the `authorization` header matches the value of `bearerType`. Additionally the string length comparison allows for the scheme to be one character shorter.

### Steps to Reproduce

Create `server.mjs`:
```js
import Fastify from "fastify";
import auth from "@fastify/bearer-auth";

const fastify = Fastify();
await fastify.register(auth, { keys: ["abc"] });
fastify.get("/", () => "ok");

await fastify.listen({ port: 3000 });
```

Run:
```sh
node server.mjs &
curl "http://localhost:3000" -H 'authorization: AAAAA abc'
```

### Expected Behavior

The server should respond with `401 Unauthorized` if the authorization scheme does not match `bearerType`.

### PR DESCRIPTION
**Pull request by dancastillo**
#### Checklist

This PR fixes issue where any string with same length as `bearer` passes validation ex: `AAAAAA auth_key`.
fixes https://github.com/fastify/fastify-bearer-auth/issues/164
 
- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/verifyBearerAuthFactory.js [hunk 1]
```diff
@@ -36,10 +35,19 @@ module.exports = function verifyBearerAuthFactory (options) {
...
+    }
+
+    const header = request.raw.headers.authorization
+    if (!header) {
+      return authorizationHeaderErrorFn('missing authorization header')
     }
 
     const key = header.substring(bearerType.length).trim()
+    const type = header.substring(0, bearerType.length)
+    if (type.toLowerCase() !== bearerType.toLowerCase()) {
```
Comment (Eomm) [inline lib/verifyBearerAuthFactory.js:47]: instead of calling `bearerType.toLowerCase()` for each request, could you pre-calculate it when the plugin is being registered and use the const directly?

File: lib/verifyBearerAuthFactory.js [hunk 2]
```diff
@@ -36,10 +35,19 @@ module.exports = function verifyBearerAuthFactory (options) {
...
-      return
+    }
+
+    const header = request.raw.headers.authorization
+    if (!header) {
+      return authorizationHeaderErrorFn('missing authorization header')
     }
 
     const key = header.substring(bearerType.length).trim()
+    const type = header.substring(0, bearerType.length)
```
Comment (Eomm) [inline lib/verifyBearerAuthFactory.js:46]: I would move the key declaration after the `type` check

**Review by Eomm — COMMENTED** [review]
Minor things

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/verifyBearerAuthFactory.js (hunk 1 above)
Comment (jsumners) [reply lib/verifyBearerAuthFactory.js:47]: It should be `Bearer` per rfc https://www.rfc-editor.org/rfc/rfc6750#section-2.1

**Review by Uzlopak — CHANGES_REQUESTED** [review]
I dont like it for the reason that it is doing over and over unnecessary string operations.

**Comment by Uzlopak** [comment]
@mcollina 

Should we use @fastify/error to create FST_BEARER_AUTH_MISSING_AUTHORIZATION_HEADER and FST_BEARER_AUTH_INVALID_AUTHORIZATION_HEADER  and use that instead? Would also be better passing them to the callback instead of native Node Errors?

**Comment by mcollina** [comment]
1. yes
2. as you prefer, what is there now is ok.

**Comment by Uzlopak** [comment]
I am ok with this. I would probably create a follow up PR in the few days to straighten this up.

**Review by Uzlopak — APPROVED** [review]

**Comment by olivierchatry** [comment]
Is verifying authtype suppose to be case sensitive ? I'm think it should not be. Found this : https://github.com/lexik/LexikJWTAuthenticationBundle/issues/411
